name: "tinytalk theme"
description: "Tinytalk theme"

url: ''
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: _sass

