#page title
page_title                                : Tiny Talk                                 # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : /signup                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : /signup                                   # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/tinytalk.png                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Tiny Talk                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Tiny Talk is a semi-social media app focused on creating meaningful, human to human connections through short, randomly coordinated video chats with your contacts.
app_description2                          : It's like Chat Roulette, but with your friends.


enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Tiny Talk Inc.
your_link                                 :
your_city                                 : Denver, CO
email_address                             : team@tinytalk.io
facebook_username                         :
instagram_username                        : TinyTalkInc
twitter_username                          : TinyTalkInc
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Sort
    description                           : Sort or block your contacts to generate the list of people you're eligible to Tiny Talk with. Other Tiny Talk users will never know if you've blocked them.
    fontawesome_icon_name                 : magic

  - title                                 : Match
    description                           : From time to time, the app will invite you to join a Tiny Talk with one of your contacts, chosen randomly. You won't know who they are -- and neither will they -- until you both opt-in and are matched. You can also manually initiate a Tiny Talk anytime, and it works exactly the same way.
    fontawesome_icon_name                 : mobile

  - title                                 : Chat
    description                           : Once a match has been made, you'll be automatically connected for a seven-minute video chat. At the end of seven minutes, the chat will end -- that's it! Tiny Talks are hors d'oeuvres -- if you're still hungry, just call the person back.
    fontawesome_icon_name                 : play-circle



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
